apiVestion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
spec:
  rules:
  - http:
    paths:
    - path: /
      pathType: Prefix
      backend:
        service:
          name: grafana
          port:
            number: 3000
