apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 2on-frontend
spec:
  rules:
  - host: 2on.olszewskib.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 2on-frontend
            port:
              number: 8080
