apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: alloy
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: homelab
  sources:
  - chart: alloy
    helm:
      valueFiles:
      - $k8s/monitoring/alloy/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.9.2
  - ref: k8s
    repoURL: https://github.com/olszewskib/k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
